//! Round-trip properties over generated files.
//!
//! The example tests in `write.rs` sample the round trip; these state
//! it. `parse(write(f))` describing the same device as `f` is the
//! central invariant of this crate — everything M1 does to a fuse map
//! depends on it — and the interesting failures live at edges an
//! example test would have to guess at: fuse counts that are not
//! multiples of eight, all-default and all-inverted devices, single-fuse
//! runs at the very end of the vector.
//!
//! Cases are generated by proptest and shrunk on failure, so a
//! counterexample arrives minimal rather than as a 2000-fuse haystack.

use decpld_diagnostics::FileId;
use decpld_diagnostics::{Span, TextRange};
use decpld_jedec::{
    FuseVector, JedecField, JedecFile, ParserMode, WriterStyle, parse, parse_with_mode, write,
};
use proptest::prelude::*;

const FILE: FileId = FileId(0);

/// Text that a JEDEC field can legally carry.
///
/// Drawn from an alphabet chosen to be adversarial rather than
/// realistic: the characters either side of the `*` gap in JEDEC 3A's
/// `<field character>` class, the letters that decide whether an
/// identifier needs a separator, and the spaces that parse-time
/// normalisation trims. `*` and control characters are excluded — those
/// are the refusal paths, tested separately below.
fn any_body() -> impl Strategy<Value = String> {
    proptest::collection::vec(
        prop_oneof![
            Just('0'),
            Just('1'),
            Just('9'),
            Just('a'),
            Just('Z'),
            Just(' '),
            Just(')'),
            Just('+'),
            Just('~'),
            Just('$'),
        ],
        0..12,
    )
    .prop_map(|chars| chars.into_iter().collect())
}

/// Unmodelled fields over the whole space the model can hold.
///
/// Their absence hid a bug once: the writer normalised bodies on the way
/// *out*, so `QP 20*` came back as `QP20*` and a file differed from its
/// own canonicalisation. The first fix generated five realistic fields —
/// whose bodies all began with a digit or a space, making it
/// structurally incapable of producing the `Z custom` -> `Zcustom`
/// corruption found later by hand.
///
/// So the identifiers now span all three JEDEC classes (defined,
/// reserved, and not-an-identifier-at-all) and the bodies are arbitrary.
/// A generator that can only produce the cases someone already thought
/// of is a generator that can only find the bugs someone already found.
fn any_unknown_fields() -> impl Strategy<Value = Vec<JedecField>> {
    let identifier = prop_oneof![
        // Value fields, which the writer must hoist ahead of the fuse
        // data, and testing fields, which it must not.
        Just("QP"),
        Just("QV"),
        Just("V"),
        Just("X"),
        Just("P"),
        // Defined but unmodelled, including the `T` that was missing
        // from the identifier table entirely.
        Just("A"),
        Just("T"),
        Just("R"),
        // Reserved: JEDEC 3A tells receivers to ignore these, and they
        // must still survive a rewrite.
        Just("J"),
        Just("Z"),
        // A Q subfield outside the three the standard defines.
        Just("QX"),
        // No identifier at all — legal for the model to hold, and the
        // shape that used to be silently deleted.
        Just(""),
    ];

    let field = (identifier, any_body()).prop_map(|(identifier, body)| JedecField {
        identifier: identifier.to_owned(),
        body,
        span: Span::new(FILE, TextRange::empty_at(0)),
    });

    // Value fields first, matching the canonical order the parser
    // establishes. A `JedecFile` is expected to hold them that way —
    // JEDEC 3A requires value fields before programming and testing
    // fields, so a model that stored them interleaved would describe a
    // file that cannot legally be written. The writer hoists too, so a
    // hand-built file still comes out conformant; that path has its own
    // example test.
    proptest::collection::vec(field, 0..4).prop_map(|mut fields| {
        fields.sort_by_key(|f| !f.is_value_field());
        fields
    })
}

/// Notes, including the shapes parse-time normalisation changes.
///
/// Hard-coded to `Vec::new()` before, so a file with
/// `notes: ["  spaced  "]` did not round-trip and nothing noticed:
/// `write` returned `Ok` and silently changed the note.
fn any_notes() -> impl Strategy<Value = Vec<String>> {
    proptest::collection::vec(any_body(), 0..3)
}

/// Headers, including the empty one JEDEC cannot express the absence of.
fn any_header() -> impl Strategy<Value = String> {
    prop_oneof![Just(String::new()), Just("generated".to_owned()), any_body()]
}

/// The normal form a parse produces.
///
/// The parser trims field bodies and notes, so a model holding
/// `"  spaced  "` describes a file that cannot be written back as
/// itself — `write` refuses it, correctly. Normalising here lets the
/// round-trip properties state "this always writes", which is a stronger
/// and more useful claim than "this writes when it happens to".
///
/// The refusal path is not lost by doing this: it is asserted directly
/// by the properties at the end of this file, over *un*-normalised
/// files.
fn normalise(mut file: JedecFile) -> JedecFile {
    file.notes = file.notes.iter().map(|note| note.trim().to_owned()).collect();
    file.unknown_fields = file
        .unknown_fields
        .into_iter()
        .map(|mut field| {
            field.body = field.body.trim().to_owned();
            field
        })
        // A field with no identifier whose body starts with a letter has
        // no JEDEC spelling: written out, the body becomes the
        // identifier. Excluded here because it is unrepresentable, not
        // because it is awkward — `a_refusal_is_always_justified` below
        // is what checks the writer says so.
        .filter(|field| {
            !(field.identifier.is_empty()
                && field.body.starts_with(|c: char| c.is_ascii_alphabetic()))
        })
        .collect();
    file
}

/// A file with an arbitrary fuse vector, default state, and metadata.
fn any_jedec_file() -> impl Strategy<Value = JedecFile> {
    // Fuse counts deliberately include values that are not multiples of
    // eight, where the final partial word's padding bits decide whether
    // the checksum is right — and 0, which is a legal `QF` and the edge
    // every "for each fuse" loop gets wrong first.
    //
    // `default_fuse` is an Option, and `None` — a file that carries no
    // `F` field because it states every fuse explicitly — is a distinct
    // state the writer handles differently in BOTH styles. Generating
    // only `Some` would leave the round trip blind to it.
    (
        0usize..300,
        proptest::option::of(any::<bool>()),
        any_header(),
        proptest::option::of(any::<bool>()),
    )
        .prop_flat_map(|(count, default, header, security)| {
            (
                proptest::collection::vec(any::<bool>(), count),
                Just(default),
                Just(header),
                Just(security),
                any_unknown_fields(),
                any_notes(),
            )
        })
        .prop_map(|(states, default_fuse, header, security, unknown_fields, notes)| {
            let mut fuses = FuseVector::new(states.len() as u32, default_fuse.unwrap_or(false));
            for (index, state) in states.iter().enumerate() {
                fuses.set(index as u32, *state).expect("in range by construction");
            }
            JedecFile {
                design_specification: header,
                fuses,
                default_fuse,
                notes,
                security,
                fuse_checksum: None,
                transmission_checksum: None,
                unknown_fields,
            }
        })
        .prop_map(normalise)
}

/// A file whose content is conformant JEDEC 3A, not merely
/// representable.
///
/// The difference is the identifier-less field: the model can hold one
/// and a rewrite must preserve it, but the standard has no such field,
/// so strict mode rejects it. A property that parses its own output in
/// strict mode has to exclude it or it is testing two things and
/// blaming the wrong one.
fn any_conformant_jedec_file() -> impl Strategy<Value = JedecFile> {
    any_jedec_file().prop_map(|mut file| {
        file.unknown_fields.retain(|field| !field.identifier.is_empty());
        file
    })
}

/// As [`any_jedec_file`], but *without* normalisation — so it generates
/// content the writer must refuse as well as content it must accept.
fn any_possibly_unwritable_file() -> impl Strategy<Value = JedecFile> {
    (
        0usize..40,
        proptest::option::of(any::<bool>()),
        any_header(),
        any_unknown_fields(),
        any_notes(),
    )
        .prop_map(|(count, default_fuse, header, unknown_fields, notes)| JedecFile {
            design_specification: header,
            fuses: FuseVector::new(count as u32, default_fuse.unwrap_or(false)),
            default_fuse,
            notes,
            security: None,
            fuse_checksum: None,
            transmission_checksum: None,
            unknown_fields,
        })
}

proptest! {
    #[test]
    fn canonical_output_round_trips(file in any_jedec_file()) {
        let text = write(&file, WriterStyle::Canonical).expect("writes");
        let reparsed = parse(&text, FILE).expect("our own output must parse").file;
        prop_assert!(
            file.describes_same_device_as(&reparsed),
            "round trip changed the file:\n{text}"
        );
    }

    #[test]
    fn compact_output_round_trips(file in any_jedec_file()) {
        // Compact only states fuses differing from the default, so it
        // exercises run detection: a bug in the run boundaries shows up
        // here and nowhere else.
        let text = write(&file, WriterStyle::Compact).expect("writes");
        let reparsed = parse(&text, FILE).expect("our own output must parse").file;
        prop_assert!(
            file.describes_same_device_as(&reparsed),
            "round trip changed the file:\n{text}"
        );
    }

    #[test]
    fn both_styles_describe_the_same_device(file in any_jedec_file()) {
        // Canonical states every fuse; compact states only the
        // surprising ones. They are different bytes and must be the same
        // device — this is what makes "compact" a style rather than a
        // lossy shortcut.
        let canonical = parse(&write(&file, WriterStyle::Canonical).unwrap(), FILE).unwrap().file;
        let compact = parse(&write(&file, WriterStyle::Compact).unwrap(), FILE).unwrap().file;
        prop_assert!(canonical.describes_same_device_as(&compact));
    }

    #[test]
    fn written_files_satisfy_their_own_checksums(file in any_conformant_jedec_file()) {
        // Strict mode verifies both checksums and requires the
        // transmission checksum to be present, so a successful strict
        // parse of our own output is the strongest statement available
        // that the writer computed them correctly.
        let text = write(&file, WriterStyle::Canonical).expect("writes");
        prop_assert!(parse_with_mode(&text, FILE, ParserMode::Strict).is_ok());
    }

    #[test]
    fn writing_is_idempotent(file in any_jedec_file()) {
        // `decpld jed canonicalize` run twice must not churn the file.
        let once = write(&file, WriterStyle::Canonical).expect("writes");
        let twice =
            write(&parse(&once, FILE).unwrap().file, WriterStyle::Canonical).expect("writes");
        prop_assert_eq!(once, twice);
    }

    #[test]
    fn the_fuse_checksum_is_independent_of_style(file in any_jedec_file()) {
        // The checksum covers the device, not the notation. Two styles
        // disagreeing would mean one of them is losing or inventing a
        // fuse.
        let canonical = parse(&write(&file, WriterStyle::Canonical).unwrap(), FILE).unwrap().file;
        let compact = parse(&write(&file, WriterStyle::Compact).unwrap(), FILE).unwrap().file;
        prop_assert_eq!(
            canonical.computed_fuse_checksum(),
            compact.computed_fuse_checksum()
        );
    }
}

proptest! {
    #[test]
    fn a_normalised_file_always_writes(file in any_jedec_file()) {
        // The generator produces content already in the form a parse
        // yields, so refusal here would mean the writer cannot encode
        // something it just read — the one outcome that would make
        // `canonicalize` unusable.
        //
        // Stated separately from the round-trip properties because those
        // would also pass if `write` refused everything and `expect`
        // never ran: proptest reports a panic, but a property that only
        // ever runs on an empty set is not a property.
        prop_assert!(
            write(&file, WriterStyle::Canonical).is_ok(),
            "refused content a parse could have produced: {file:#?}"
        );
    }

    #[test]
    fn write_never_returns_text_that_reads_back_differently(
        file in any_possibly_unwritable_file()
    ) {
        // Over arbitrary content, including content that cannot be
        // encoded. The writer may refuse — that is the point — but it
        // must never hand back a string that means something else.
        //
        // This is the invariant the internal guard exists to hold, and
        // asserting it from outside is what would notice if the guard
        // were ever made conditional or removed.
        if let Ok(text) = write(&file, WriterStyle::Canonical) {
            let reparsed = parse(&text, FILE).expect("our own output must parse").file;
            prop_assert!(
                file.describes_same_device_as(&reparsed),
                "write returned text describing a different file:\n{text}"
            );
        }
    }

    #[test]
    fn a_refusal_is_always_justified(file in any_possibly_unwritable_file()) {
        // The converse, and the one #23 actually asks for: refusing is
        // only honest if the content genuinely cannot be encoded.
        //
        // "Genuinely" is checked by construction rather than by trusting
        // the error: normalise the file — the only transformation a
        // parse would have applied anyway — and it must then write. A
        // writer that refused something normalisation could have saved
        // is a writer refusing for its own convenience.
        if write(&file, WriterStyle::Canonical).is_err() {
            let normalised = normalise(file.clone());
            prop_assert!(
                write(&normalised, WriterStyle::Canonical).is_ok(),
                "refused a file that normalisation makes writable, so the refusal was not \
                 about encodability:\nbefore: {file:#?}\nafter: {normalised:#?}"
            );
        }
    }

    #[test]
    fn refusing_is_deterministic(file in any_possibly_unwritable_file()) {
        // SPEC.md §5.32. A refusal that depended on anything ambient
        // would make `canonicalize` fail intermittently, which is worse
        // than failing.
        prop_assert_eq!(
            write(&file, WriterStyle::Canonical).is_ok(),
            write(&file, WriterStyle::Canonical).is_ok()
        );
    }

    #[test]
    fn a_zero_fuse_device_is_handled_like_any_other(
        default_fuse in proptest::option::of(any::<bool>())
    ) {
        // `QF0` is legal and is the edge every "for each fuse" loop gets
        // wrong first. The old generator started at 1, so nothing
        // exercised it — including the coverage check, where an empty
        // device is vacuously complete.
        let file = JedecFile {
            design_specification: "empty".to_owned(),
            fuses: FuseVector::new(0, false),
            default_fuse,
            notes: Vec::new(),
            security: None,
            fuse_checksum: None,
            transmission_checksum: None,
            unknown_fields: Vec::new(),
        };
        for style in [WriterStyle::Canonical, WriterStyle::Compact] {
            let text = write(&file, style).expect("a zero-fuse device is writable");
            let reparsed = parse(&text, FILE).expect("and readable").file;
            prop_assert!(file.describes_same_device_as(&reparsed), "{style:?}:\n{text}");
            prop_assert_eq!(reparsed.fuses.len(), 0);
        }
    }
}
