//! Round-trip properties over generated files.
//!
//! The example tests in `write.rs` sample the round trip; these state
//! it. `parse(write(f))` describing the same device as `f` is the
//! central invariant of this crate — everything M1 does to a fuse map
//! depends on it — and the interesting failures live at edges an
//! example test would have to guess at: fuse counts that are not
//! multiples of eight, all-default and all-inverted devices, single-fuse
//! runs at the very end of the vector.
//!
//! Cases are generated by proptest and shrunk on failure, so a
//! counterexample arrives minimal rather than as a 2000-fuse haystack.

use decpld_diagnostics::FileId;
use decpld_diagnostics::{Span, TextRange};
use decpld_jedec::{
    FuseVector, JedecField, JedecFile, ParserMode, WriterStyle, parse, parse_with_mode, write,
};
use proptest::prelude::*;

const FILE: FileId = FileId(0);

/// Unmodelled fields, drawn from real JEDEC identifiers.
///
/// Included because their absence hid a bug: the writer normalised field
/// bodies on the way *out*, so `QP 20*` came back as `QP20*` and a file
/// differed from its own canonicalisation. A property that never
/// generated these could not have found it — which is the argument for
/// generating every field the model can hold, not just the interesting
/// ones.
fn any_unknown_fields() -> impl Strategy<Value = Vec<JedecField>> {
    let field = prop_oneof![
        // A value field, which the writer must hoist ahead of the fuse
        // data, and a testing field, which it must not.
        Just(("QP", "20")),
        Just(("QV", "8")),
        Just(("V", "0001 XXXXNHHHL")),
        Just(("X", "0")),
        Just(("P", "1 2 3 4")),
    ]
    .prop_map(|(identifier, body)| JedecField {
        identifier: identifier.to_owned(),
        body: body.to_owned(),
        span: Span::new(FILE, TextRange::empty_at(0)),
    });
    // Value fields first, matching the canonical order the parser
    // establishes. A `JedecFile` is expected to hold them that way —
    // JEDEC 3A requires value fields before programming and testing
    // fields, so a model that stored them interleaved would describe a
    // file that cannot legally be written. The writer hoists too, so a
    // hand-built file still comes out conformant; that path has its own
    // example test.
    proptest::collection::vec(field, 0..4).prop_map(|mut fields| {
        fields.sort_by_key(|f| !f.is_value_field());
        fields
    })
}

/// A file with an arbitrary fuse vector, default state, and metadata.
fn any_jedec_file() -> impl Strategy<Value = JedecFile> {
    // Fuse counts deliberately include values that are not multiples of
    // eight, where the final partial word's padding bits decide whether
    // the checksum is right.
    (1usize..300, any::<bool>(), any::<bool>(), proptest::option::of(any::<bool>()))
        .prop_flat_map(|(count, default, has_header, security)| {
            (
                proptest::collection::vec(any::<bool>(), count),
                Just(default),
                Just(has_header),
                Just(security),
                any_unknown_fields(),
            )
        })
        .prop_map(|(states, default_fuse, has_header, security, unknown_fields)| {
            let mut fuses = FuseVector::new(states.len() as u32, default_fuse);
            for (index, state) in states.iter().enumerate() {
                fuses.set(index as u32, *state).expect("in range by construction");
            }
            JedecFile {
                design_specification: if has_header {
                    "generated".to_owned()
                } else {
                    String::new()
                },
                fuses,
                default_fuse,
                notes: Vec::new(),
                security,
                fuse_checksum: None,
                transmission_checksum: None,
                unknown_fields,
            }
        })
}

proptest! {
    #[test]
    fn canonical_output_round_trips(file in any_jedec_file()) {
        let text = write(&file, WriterStyle::Canonical).expect("writes");
        let reparsed = parse(&text, FILE).expect("our own output must parse").file;
        prop_assert!(
            file.describes_same_device_as(&reparsed),
            "round trip changed the file:\n{text}"
        );
    }

    #[test]
    fn compact_output_round_trips(file in any_jedec_file()) {
        // Compact only states fuses differing from the default, so it
        // exercises run detection: a bug in the run boundaries shows up
        // here and nowhere else.
        let text = write(&file, WriterStyle::Compact).expect("writes");
        let reparsed = parse(&text, FILE).expect("our own output must parse").file;
        prop_assert!(
            file.describes_same_device_as(&reparsed),
            "round trip changed the file:\n{text}"
        );
    }

    #[test]
    fn both_styles_describe_the_same_device(file in any_jedec_file()) {
        // Canonical states every fuse; compact states only the
        // surprising ones. They are different bytes and must be the same
        // device — this is what makes "compact" a style rather than a
        // lossy shortcut.
        let canonical = parse(&write(&file, WriterStyle::Canonical).unwrap(), FILE).unwrap().file;
        let compact = parse(&write(&file, WriterStyle::Compact).unwrap(), FILE).unwrap().file;
        prop_assert!(canonical.describes_same_device_as(&compact));
    }

    #[test]
    fn written_files_satisfy_their_own_checksums(file in any_jedec_file()) {
        // Strict mode verifies both checksums and requires the
        // transmission checksum to be present, so a successful strict
        // parse of our own output is the strongest statement available
        // that the writer computed them correctly.
        let text = write(&file, WriterStyle::Canonical).expect("writes");
        prop_assert!(parse_with_mode(&text, FILE, ParserMode::Strict).is_ok());
    }

    #[test]
    fn writing_is_idempotent(file in any_jedec_file()) {
        // `decpld jed canonicalize` run twice must not churn the file.
        let once = write(&file, WriterStyle::Canonical).expect("writes");
        let twice =
            write(&parse(&once, FILE).unwrap().file, WriterStyle::Canonical).expect("writes");
        prop_assert_eq!(once, twice);
    }

    #[test]
    fn the_fuse_checksum_is_independent_of_style(file in any_jedec_file()) {
        // The checksum covers the device, not the notation. Two styles
        // disagreeing would mean one of them is losing or inventing a
        // fuse.
        let canonical = parse(&write(&file, WriterStyle::Canonical).unwrap(), FILE).unwrap().file;
        let compact = parse(&write(&file, WriterStyle::Compact).unwrap(), FILE).unwrap().file;
        prop_assert_eq!(
            canonical.computed_fuse_checksum(),
            compact.computed_fuse_checksum()
        );
    }
}
